### ISSUE TITLE
About mixing parameter u in the mLFR 

### ISSUE THREAD

**Issue by sakuracg** [pbrodka/mLFR-benchmark#3]
Hello Professor
I would like to ask how the mixing parameter u in the mLFR generation algorithm affects the strength of the community structure. In other words, what is the difference between LFR and mLFR when I set u=0.1 versus setting u=0.3. The meaning of the mixing parameter u in the LFR network is to control the ratio of the number of edges outside the community to the degree of the node. So my purpose is to know how the mixing parameter u in mLFR controls the strength of the multi-layer network community.
By reading your PhD dissertation, I don't find a detailed introduction to this. Would like to ask about your knowledge about this, or it exists in your PhD thesis but I don't see it.
Thank you so much for being able to see this news! Thank you so much for being able to guide me! Thanks! ! !

**Comment by pbrodka** [comment]
Hi,

I have not worked on that for a few years now, but I will try to help you as much as I can.
As you mentioned, the most important parameter of LFR is the mixing parameter which expresses the proportion between the external degree of a node and the total degree of the node i. The mixing parameter values can range from 0 to 1 inclusive, where setting the value of between 0 and 0.5 yields a community structure, and for values above, the existence of communities is less likely. 
mLFR uses LFR to create a base layer of a multilayer network and, based on it, builds the next layers of the network, trying to keep the “assigned” distribution of edges between nodes and swapping degrees of nodes within the community if necessary etc. (see pp 88-94, 159-160). 
Since we use the LFR network as a base layer and have few other mechanisms that keep the ratio of the external and total degree of each node i (i.e., mixing parameter), the mixing parameter  will work exactly the same way in mLFR and LFR

Best
PB

**Comment by sakuracg** [comment]
Thank you very much for your answer, it will help me in my work, thank you again for helping me outside of work!!!
